"""Scaffolding logic for `evalforge init`.

Creates evalforge.yaml, test-suites/example/suite.yaml, and .gitignore
for bootstrapping a new EvalForge project.
"""

from pathlib import Path


EXAMPLE_SUITE_YAML = """\
name: Example Suite
description: A sample test suite for EvalForge
tests:
  - id: hello-exact
    prompt: "Reply with just the word: Hello"
    expected:
      type: exact
      value: "Hello"
  - id: capital-question
    prompt: "What is the capital of France?"
    expected:
      type: exact
      value: "Paris"
  - id: tone-evaluation
    prompt: "Explain quantum computing to a 5-year-old."
    expected:
      type: rubric
      value: null
      rubric:
        dimensions:
          - name: clarity
            description: "Is the explanation clear and simple?"
            weight: 0.4
          - name: accuracy
            description: "Is the information factually correct?"
            weight: 0.4
          - name: engagement
            description: "Is the explanation engaging for a child?"
            weight: 0.2
"""

CONFIG_YAML = """\
# EvalForge Configuration
# Generated by `evalforge init`

baseline_dir: evalforge-baselines/
suites:
  - path: test-suites/example/suite.yaml
    allowed_regression_pct: 5.0

judge:
  provider: deepseek
  model: deepseek-v4-flash

target:
  provider: deepseek
  model: deepseek-v4-flash

concurrency: 10
"""

GITIGNORE_CONTENT = """\
# EvalForge output
evalforge-output/

# Baselines
evalforge-baselines/

# Python
__pycache__/
*.pyc
.venv/
"""


def scaffold_project(target_dir: Path, force: bool = False) -> None:
    """Scaffold a new EvalForge project in the target directory.

    Creates:
        - evalforge.yaml (config file)
        - test-suites/example/suite.yaml (example suite)
        - .gitignore (for evalforge-output/)

    Args:
        target_dir: Directory to scaffold into. Created if missing.
        force: If True, overwrite existing files without prompting.
               If False and evalforge.yaml exists, raises FileExistsError.

    Raises:
        FileExistsError: If evalforge.yaml exists and force is False.
    """
    target_dir = target_dir.resolve()
    target_dir.mkdir(parents=True, exist_ok=True)

    config_path = target_dir / "evalforge.yaml"

    # Check for existing config
    if config_path.exists() and not force:
        raise FileExistsError(
            f"evalforge.yaml already exists in {target_dir}. "
            "Use --force to overwrite."
        )

    # Write config
    config_path.write_text(CONFIG_YAML)

    # Create test-suites/example/
    suites_dir = target_dir / "test-suites" / "example"
    suites_dir.mkdir(parents=True, exist_ok=True)

    suite_path = suites_dir / "suite.yaml"
    suite_path.write_text(EXAMPLE_SUITE_YAML)

    # Create .gitignore
    gitignore_path = target_dir / ".gitignore"
    if gitignore_path.exists() and not force:
        # Append to existing .gitignore
        existing = gitignore_path.read_text()
        if "evalforge-output" not in existing:
            gitignore_path.write_text(
                existing.rstrip() + "\n\n" + GITIGNORE_CONTENT
            )
    else:
        gitignore_path.write_text(GITIGNORE_CONTENT)
